# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Newyuanmeng' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  	
	use_frameworks!
	pod 'Alamofire', '~> 4.0'
	pod 'Kingfisher', '~> 4.0'
	pod 'SwiftyJSON'
	pod 'AMapLocation'
	pod 'AMap3DMap'
	pod 'RongCloudIM/IMLib', '~> 2.8.3'
	pod 'RongCloudIM/IMKit', '~> 2.8.3' 
	pod 'FSCalendar' 
	pod 'AFNetworking', '~> 3.0'
	pod 'MJExtension'
	pod 'MJRefresh'
	pod 'SVProgressHUD'
	pod 'IconFont', '~> 0.0.2'	
	pod 'JSONModel'
	pod 'JPushSDK', '~> 1.8.2'
	pod 'Masonry'
	pod 'PNChart'
	pod 'SDCycleScrollView','~> 1.75'
	pod 'SDWebImage', '~> 4.0'
	pod 'mob_smssdk'

  # Pods for Newyuanmeng

end
